#App properties
spring.application.name=SquaredStart
spring.datasource.url=jdbc:postgresql://localhost:5432/squared
spring.datasource.username=postgres
spring.datasource.password=postgres
server.servlet.context-path=/api

#Securiy
server.port=443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=jrgs
server.ssl.key-store-password=spring
