spring.application.name=SquaredStart
spring.datasource.url=jdbc:postgresql://localhost:5432/squared
spring.datasource.username=postgres
spring.datasource.password=postgres
server.servlet.context-path=/api
